### ISSUE TITLE
Conflict when using d3wordcloud with networkD3

### ISSUE THREAD

**Issue by sherrylau** [jbkunst/d3wordcloud#10]
Hi,

Thank you so much for working on this great package! It is very helpful to visualize the result on shiny. I was using simpleNetwork under the networkD3 packages (https://christophergandrud.github.io/networkD3/) along with your d3wordcloud packages. 

Somehow, it render perfectly fine under local for both d3wordcloud and simplenetwork. It works also fine if i render on shiny for simpleNetwork or d3wordcloud by itself. But it doesnt show both together and doesnt give me any error message. Could you please help me with this?

Thanks,
Sherry

**Comment by jbkunst** [comment]
Hi! 

Can you give me an example to replicate in my pc and start to debugging?

Probably is an issue with the d3 version.

**Comment by sherrylau** [comment]
Sure, 

For the app below, it only shows the simpleNetworkOutput graph but not the wordcloud. If i comment out that line, i can see the output for wordcloud.

``` R
app = shinyApp(
  ui = bootstrapPage(
    p("Word Cloud"),
    d3wordcloudOutput("wordCloud"),
    simpleNetworkOutput("networkGraph")
    ),
  server = function(input,output,session){
    library(tm)
    data("acq")
    corpus = acq
    dtm = DocumentTermMatrix(corpus)

    output$wordCloud = renderD3wordcloud({
      dtm = as.matrix(dtm)
      freq = colSums(dtm)
      freq = sort(freq, decreasing=TRUE)
      freqDF = data.frame(Word=rownames(data.frame(freq)),Frequency=freq)
      freqDF = freqDF[freqDF$Frequency>=10,]
      d3wordcloud(freqDF$Word, freqDF$Frequency)
    })

    networkGraphPreprocess = reactive({
      dtm_mtx = t(as.matrix(dtm))
      dtm_mtx[dtm_mtx>=1] = 1
      termMatrix = dtm_mtx %*% t(dtm_mtx)
      g = graph.adjacency(termMatrix, weighted=T, mode="undirected")
      g = simplify(g, remove.multiple=TRUE, remove.loops=TRUE)
      V(g)$label = V(g)$name
      V(g)$degree = degree(g)
      g2 = induced.subgraph(g, E(g)[neighbors(g,"withdrawal")])
      g2
    })

    output$networkGraph = renderSimpleNetwork({
      g2 = networkGraphPreprocess()
      g2 = get.data.frame(g2)
      colnames(g2) = c("Source","Target","Weight")
      simpleNetwork(g2, 
                    width=550, 
                    height=550,
                    fontSize = 10,
                    textColour = "#4f372d",
                    linkColour = "#4f372d",
                    nodeColour = "#cc2a36",
                    nodeClickColour = "#00a0b0",
                    opacity=0.8)
    })

  }
)
runApp(app)
```

**Comment by jbkunst** [comment]
Hi @sherrylau,

Please, download again and tell me if now your example works.

Aps, the next time please provide all the requiriments ;)

```
library("shiny")
library("networkD3")
library("d3wordcloud")
library("igraph")
```

it is easier / faster to reproduce the examples.

**Comment by sherrylau** [comment]
It works perfectly! Thanks for your help!

Sherry

**Comment by jbkunst** [comment]
Thank you for notice this error!
