### ISSUE TITLE
OnClick functionality ?

### ISSUE THREAD

**Issue by venusathya** [jbkunst/d3wordcloud#12]
The word cloud is really awesome with manny cool features. In the word cloud created by JJason Davies. click funcitonality was there, but in this wrapper the click functionality is replaced by tooltip. Is it possible to have the on click functionlaity for each word in this word cloud as well?

**Comment by jbkunst** [comment]
Hi @venusathya 

The click funcionality was not replaced. The event used in the tooltip is [mouseover](https://github.com/jbkunst/d3wordcloud/blob/master/inst/htmlwidgets/d3wordcloud.js#L181), so the click is available ;). Can you give me a situacion when the funcionality is needed (besides to send information to shiny, which is a nice feature)?

**Comment by venusathya** [comment]
Hi joshua,

Apologies for replying late. I was using the on click functionality to
display the comments that contained the word in the word cloud. For example
if there is a word say "recommend" in the word cloud, when the user clicks
on the word I will display all the comments containing the word "recommend".

Thanks and regards,
Venugopal s

**Comment by jpmarindiaz** [comment]
I just made a pull request on something related to this issue. Basically I added a small option to send back to shiny the word that was clicked, simply use: `input$d3wordcloud_click` in your `server.R`. From there you can use any shiny magic to display more info about the word clicked.

**Comment by jbkunst** [comment]
Hi @jpmarindiaz 

Ok! it's fine for me ;). Thanks.
