### ISSUE TITLE
How to use it in html with JS?

### ISSUE THREAD

**Issue by iamwelk** [jbkunst/d3wordcloud#21]
Excuse me, I want to render a word cloud in HTML, how to use the package?

**Comment by timelyportfolio** [comment]
@iamwelk I assume you mean save the `d3wordcloud` as a standalone html document.  If I assume correctly, we can accomplish this by

```
htmlwidgets::saveWidget(
  d3wordcloud(words, freqs),
  "index.html"
)
```
