### ISSUE TITLE
d3wordcloud’ is not available (for R version 3.5.1)

### ISSUE THREAD

**Issue by vneeruk** [jbkunst/d3wordcloud#28]
It seems, you haven't committed in a while. Is it possible to commit package for latest version of R. I tried with lower version of R 3.4.1 didnt worked out.

**Comment by jbkunst** [comment]
The package does not required an specific R version. Did you tried this https://github.com/jbkunst/d3wordcloud#how-can-you-get-it right?

**Comment by vneeruk** [comment]
It worked,  directly installing from Git source.  Thanks

**Comment by jbkunst** [comment]
You had that message because this package is not on CRAN.
