### ISSUE TITLE
tooltip?

### ISSUE THREAD

**Issue by ignacio82** [jbkunst/d3wordcloud#7]
Is it possible to add a tool-tip that shows, for example, the frequency of the word?
Thanks for the great package!

**Comment by jbkunst** [comment]
Yeah, it's possible. Im just worried about performance when you put a 500+ words, but obviously this could be an option (default false) and responsability for the user.

Give me some time and I will try add this funcionality.

Thank you for use the package!

**Comment by jbkunst** [comment]
@ignacio82 

Ok, I add a minimal tooltip funcionality, adding `tooltip=TRUE`. Please. check [here](http://rstudio-pubs-static.s3.amazonaws.com/133106_df80b0877cfe45f2b8f06c03c60ffcab.html#tooltips) and tell me if it help ;).

**Comment by ignacio82** [comment]
@jbkunst looks great! Thanks!
