### ISSUE TITLE
bug (?) missing words

### ISSUE THREAD

**Issue by ignacio82** [jbkunst/d3wordcloud#8]
In this simple example only 1 of the 3 'words' is plotted.

```
words <-
  structure(c(223L, 193L, 146L), .Dim = 3L, .Dimnames = structure(list(
    c(
      "CERTIFIED SERVICE MANAGER (CSM)", "CISCO CERTIFIED NETWORK ASSOCIATE",
      "CISCO CERTIFIED NETWORK PROFESSIONAL (CCNP)"
    )
  ), .Names = ""))

library("d3wordcloud")
set.seed(8297)   
d3wordcloud(words= names(words), freqs = as.numeric(words), font = 'impact')
```

`wordcloud` plots the 3:

```
library(wordcloud)
wordcloud(names(words),as.numeric(words), scale = c(1.5, 0.25))
```

Thanks!

**Comment by jbkunst** [comment]
Mmm.. I think your 'words' are too long ;). I'm don't know a quick way to fix this because I only use the https://github.com/jasondavies/d3-cloud library and I am not a d3js expert. I don't think this is a bug, may be a extreme/rare case where wordcloud dont fit in the needs. 

I will think about this, if I can do something I let you know.

By the way, I tried use the wordcloud package and it says:

wordcloud(names(words),as.numeric(words), scale = c(1.5, 0.25))
Warning messages:
    1: In wordcloud(names(words), as.numeric(words), scale = c(1.5, 0.25)) :
      CISCO CERTIFIED NETWORK ASSOCIATE could not be fit on page. It will not be plotted.
    2: In wordcloud(names(words), as.numeric(words), scale = c(1.5, 0.25)) :
      CERTIFIED SERVICE MANAGER (CSM) could not be fit on page. It will not be plotted.
    3: In wordcloud(names(words), as.numeric(words), scale = c(1.5, 0.25)) :
      CISCO CERTIFIED NETWORK PROFESSIONAL (CCNP) could not be fit on page. It will not be plotted.

**Comment by ignacio82** [comment]
@jbkunst Thanks! The wordcloud package works fine for me. My guess is that your screen has a lower resolution than mine (or something like that)

**Comment by jbkunst** [comment]
@ignacio82 sure, this must be it.

**Comment by ignacio82** [comment]
is there a bug fix? I just tried and I get the same behavior.

**Comment by jbkunst** [comment]
Oops, Not yet.

I'm just noticed the discuss on jasondavies/d3-cloud#36. I dont know if the solutions presented in that issue are easy to implement. I'll check, so if there are an easy one I'll implement in other case we close the issue.

**Comment by jbkunst** [comment]
@ignacio82 

Ok, the simple solution I found it was add a resize parameter. Check [here](http://rstudio-pubs-static.s3.amazonaws.com/133106_df80b0877cfe45f2b8f06c03c60ffcab.html#change-size).

Tell me if it helps.

**Comment by ignacio82** [comment]
@jbkunst looks great! Thanks!
