### ISSUE TITLE
Possible to add filter to the plot?

### ISSUE THREAD

**Issue by sculptor3** [jbkunst/d3wordcloud#9]
Hi Joshua,

Thank you for your great package! I want to add the a wordcloud to a website. Since there is no connection with shiny I was wondering if it is possible to add a filter or some kind of control to the plot that enables the user to switch between different clouds based on different datasets or paramaters. 

Is it easy to add a feature like that? 

Kind regards,
Jelle

**Comment by jbkunst** [comment]
@sculptor3 ! Hi!

Sorry, but for me is not so easy and I think that funcionality and I think is far from the scope for this package. Maybe you can do a shiny app and put in you website via iframe. Maybe this is not the best solution but it's something.

Kind regards,
